name: dependent_test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка исходного кода
      uses: actions/checkout@v2

    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Запуск тестов
        run: |
          pytest  
