name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка исходного кода
      uses: actions/checkout@v2

    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Запуск теста и генерация репорта
      run: |
        pytest --html=report.html --self-contained-html
        
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
        
    - name: Upload code as artifact
      if: success() 
      uses: actions/upload-artifact@v4
      with:
        name: source-code
        path: .
